### ISSUE TITLE
放送中に突然uacが発生する現象への対応について

### ISSUE THREAD

**Issue by ZippermanII** [ZippermanII/VoiroGokko#6]
20200828現在未解決
　　　 31方針決定
# いつ起きるか
1.ボイロごっこが動いている最中に突然(特にコメントが増えてくると起きやすい気がする)
2.nico_comment_get.pyが配信中コミュを発見した直後

#原因考察
上記の共通点はcommentlog.xmlへの読み書きが発生しやすい状況である
1.のエラーログ発生時のニコ生画面及びエラーログ
![errorpic2](https://user-images.githubusercontent.com/39484943/91491746-77070d00-e8ef-11ea-8d14-981cff356bcd.jpg)
2.発生時のログキャプチャ
![errorpic](https://user-images.githubusercontent.com/39484943/91491789-89814680-e8ef-11ea-96b4-1c4c04633f0b.jpg)

**Comment by arigayas** [comment]
lv327768403 のタイムシフトの5時間10分ぐらいから見てコメントしてます。
`commentlog.xml` への読み書きが出来ないように
`commentlog.xml` への書き込みを禁止するテキストエディタ(*)で開いてみたら再現できるかな？

あと `タイムスタンプ + commentlog.xml `への読み書きが出来ないようにするのも試すのはいかがでしょうか？

(*)：サクラエディタで開くと確かデフォルトでは他のソフトからの書き込み禁止(ファイルの排他制御がされる)で開かれたはず。

**Comment by ZippermanII** [comment]
> `commentlog.xml` への読み書きが出来ないように
> `commentlog.xml` への書き込みを禁止するテキストエディタ(*)で開いてみたら再現できるかな？
> 
> あと `タイムスタンプ + commentlog.xml `への読み書きが出来ないようにするのも試すのはいかがでしょうか？
> 
> (*)：サクラエディタで開くと確かデフォルトでは他のソフトからの書き込み禁止(ファイルの排他制御がされる)で開かれたはず。

アイディアありがとうございます！
ご指摘のサクラエディタで「commentlog.xml読み書き禁止」状態にしてみたところ、おそらく100%でUACが発生するようです。
実稼働環境では「pyがxml書き込みをしている最中にjsの500ミリ秒間隔の読み出しがかち合ってしまう」と発生するとみるのが確実になりました。

対策を検討していきます。

**Comment by ZippermanII** [comment]
# 原因考察2
1.jsが読み込み開始(完了はまだ)
2.読み込み完了前にpyが書き出しを始めてしまう
3.pyが書き出し完了前にjsがさらに中身を読み込もうとすると弾かれてしまう
という可能性はあるだろうか？

サーバーアプリがどういった仕組みによって
「読み書き不可のファイルにアクセスした際UACの再許可」を求めているのかは依然不明。

## 原因考察2が正しかった場合の対策
1.jsの読み込み中はpyから読みださせないようにする、py側にも書き出し失敗時にリトライする仕組みを設ける。
2.サーバーアプリのUACを無効化する。

1のほうががあらゆる環境において確実
2はセキュリティや安定性において難あり

**Comment by k896951** [comment]
当方のWikiが読まれていないようなので。

ファイルの読み込みができない事によりUACが発生する可能性はあります。
※そもそもアクセス不可能なコンテンツを要求される事を想定していません

要望が不明瞭なので「簡易な検査で読み取りが可能でなければ HTTP STATUS 503 を返し、読み取りできそうならコンテンツ（今回はxml?）を送出する」との要望と仮定しましたので、 TinySeikaServer へ手を入れてみます。お試し版として公開されることになるでしょう。

ただし根本的な解決にならないことは理解してください。
TinySeikaServer が xml の送出を始めたら、送出中のファイルに Python で更新をかけられたかどうかについての関知はしません。
当然壊れた内容を送信してしまう可能性があります。
※これは他社様のHTTPサーバでも同様かと思われますが。

といいますか、頻繁にファイルを構築しなおすような構成はお勧めできません。Key-Valueストア的なモノの導入やハッシュの応用で対応することを考えるべきです。

どうしてもファイル再構築で押し通そうとするなら、ファイルの排他制御を確立して同時アクセスが発生しないようにプログラムを構築しなおすことをお勧めします。

**Comment by ZippermanII** [comment]
# 対応方針決定
現行のpyでxml書き出し→jsでxml読み込みという仕組みから変更することにしました。

jsとpyが互いに一つのxml関与してしまうという不安定な仕組みが生み出された理由は、
1.「とにかく一刻も早く動き出すものを作り出して実際の生放送で手ごたえを得る」と
2.「一つのファイルへの同時アクセスは不安定の原因という認識の欠如」により
以前自分が作り出した仕組みと他の方が提示してくださった仕組みを流用合成する手段を選んだことに起因しています。
2.はよろしくないとのご指摘をいただきましたので変更を決めました。

「動くもの」「手ごたえを得る」段階は現状の仕組みで達成、継続できると判断して
元々の予定にあった「スクリプトをjsに一本化」の変更も兼ねた
安定する仕組みへの大幅アップデートに着手することに致しました。
「手ごたえを得る」為の配信では現行の仕組みを使いつつ時間をかけて
少しずつ動くものにまでもっていくことになりそうです。
詳細実装内容は別途issueを作成します。

ご意見ありがとうございました。
